#!/bin/bash
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'

source /usr/share/makepkg/util/message.sh || exit

if [[ -t 2 && ! -o xtrace ]]; then
    colorize
fi

aur repo --list-repo | while read -r; do
    name=$(basename "$REPLY" .db)
    aur sync -d $name "$@"
done

