#!/bin/bash
readonly PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
readonly XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}
readonly AURDEST=${AURDEST:-$XDG_CACHE_HOME/aurutils/sync}
readonly AURVCS=${AURVCS:-".*-(cvs|svn|git|hg|bzr|darcs)"}

tmp=$(mktemp -d)
trap 'rm -rf -- "$tmp"' EXIT

if cd "$AURDEST"; then
    aur repo --list "$@" \
        | grep -E $AURVCS \
        | tee "$tmp"/db \
        | cut -f1 \
        | xargs -r aur srcver > "$tmp"/new || exit

    if [[ -s $tmp/new ]]; then
       aur vercmp -p "$tmp"/new < "$tmp"/db
    fi
fi
